# Laraquest (Telegram Bot API)

- Laraquest is LaraGram's Telegram Bot API client. Every Bot API method is available on `LaraGram\Request\Request` (`$request->sendMessage(...)`, `$request->call('methodName', [...])`) with the method's parameters as (named) arguments.
- Look up a method's parameters, return type, and object fields with `search-docs` and `packages: ['laraxgram/laraquest']` (for example `sendMediaGroup` or `InlineKeyboardMarkup`) instead of guessing from memory; the schema matches the installed Bot API version.
- Configure per-method default parameters (such as `parse_mode`) under `default_parameters` in `config/laraquest.php` instead of repeating them on every call.
- Never build `https://api.telegram.org/bot<token>/...` URLs or call the Bot API through the HTTP client; the request object applies the bot connection, anti-flood pacing, the proxy pool, and default parameters.
- A call gives back a response that reads three ways: the array Telegram sent (`$response['result']['message_id']`), the result's own fields (`$request->getMe()->first_name`), and helpers around it (`isOk()`, `failed()`, `result()`, `errorCode()`, `description()`, `retryAfter()`, `migrateToChatId()`, `toArray($full)`, `toJson($full)`, `throw()`). Check the result before using it.
- Failures do not throw unless asked: `$request->throw()->sendMessage(...)` (or `laraquest.throw_exceptions`) raises the exception matching the failure, and `silent()` opts a call back out. Catch the specific one - `BotBlockedException`, `ChatNotFoundException`, `MessageNotModifiedException`, `NotEnoughRightsException`, `FloodException`, `ChatMigratedException`, `ConnectionException` - instead of matching on `description` strings; they all extend `LaraGram\Laraquest\Exceptions\TelegramApiException`.
- Build the structures a call takes with the generated types (`LinkPreviewOptions::init(...)`, `ReplyParameters::init(...)`, `InputPollOption::init(...)`), and read payloads back with `Message::from($response['result'])`, which walks nested objects (`$message->chat->id`, `$message->get('from.username')`). Keyboards are the exception: use the `Keyboard` / `Make` builder.
